version: "3.9"
services:
   db:
    image: "mongo:5.0.8"
    container_name: noir-db
    volumes:
      - ${NOIR_DB_VOLUME}:/data/db
    ports:
        - ${NOIR_DB_PORT}:27017
    restart: always
   app:
    container_name: noir-app
    build:
        context: .
    environment:
        - SERVER_PORT=${NOIR_SERVER_PORT}
        - DB_HOST=db:${NOIR_DB_PORT}
    ports:
        - ${NOIR_SERVER_PORT}:${NOIR_SERVER_PORT}
    restart: always
    depends_on:
        - db